#pragma once

#define MLWE_FAST_K 2
#define MLWE_FAST_N 256
#define MLWE_FAST_Q 3329

#define MLWE_FAST_BARRETT_M 20159
#define MLWE_FAST_BARRETT_K 26

#define MLWE_FAST_QINV (-3327)
#define MLWE_FAST_MONT_R 65536
#define MLWE_FAST_INV_N_MONT 1441

#define MLWE_FAST_POLYBYTES 384
#define MLWE_FAST_POLYVECBYTES (MLWE_FAST_K * MLWE_FAST_POLYBYTES)

#ifndef MLWE_FAST_PUBLICKEYBYTES
#define MLWE_FAST_PUBLICKEYBYTES (MLWE_FAST_POLYVECBYTES + 32)
#endif

#ifndef MLWE_FAST_INDCPA_SECRETKEYBYTES
#define MLWE_FAST_INDCPA_SECRETKEYBYTES  (MLWE_FAST_POLYVECBYTES)
#endif
#define MLWE_FAST_POLYVECCOMPRESSEDBYTES (MLWE_FAST_K * 320)

#ifndef MLWE_FAST_CIPHERTEXTBYTES
#define MLWE_FAST_CIPHERTEXTBYTES (MLWE_FAST_POLYVECCOMPRESSEDBYTES + 128)
#endif

#ifndef MLWE_FAST_SSBYTES
#define MLWE_FAST_SSBYTES 32
#endif

#ifndef MLWE_FAST_SECRETKEYBYTES
#define MLWE_FAST_SECRETKEYBYTES (MLWE_FAST_INDCPA_SECRETKEYBYTES + MLWE_FAST_PUBLICKEYBYTES + 32 + 32)
#endif
